### ISSUE TITLE
Windows requires python-certifi-win32

### ISSUE THREAD

**Issue by cliffAtOsaic** [veracode/veracode-python-hmac-example#7]
Running on Windows produces the following error:

```
>python example.py
Whoops!
HTTPSConnectionPool(host='api.veracode.com', port=443): Max retries exceeded with url: /appsec/v1/applications (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
```

Solution is to install python-certifi-win32.

It doesn't make sense to add this to `requirements.txt` for all installs but perhaps it could be added to the documentation for Windows installs.

**Comment by relaxnow** [comment]
Hi @cliffAtOsaic ! Thanks for reporting this!
I looked at this but could not reproduce it on Windows. I think it requires a machine that does SSL interception which I don't have available. Could you try: https://github.com/relaxnow/veracode-python-hmac-example/commit/70883f345cc222e30fe8f76f36e29d2e70ff71d6 ?

**Comment by cliffAtOsaic** [comment]
> Hi @cliffAtOsaic ! Thanks for reporting this! I looked at this but could not reproduce it on Windows. I think it requires a machine that does SSL interception which I don't have available. Could you try: [relaxnow@70883f3](https://github.com/relaxnow/veracode-python-hmac-example/commit/70883f345cc222e30fe8f76f36e29d2e70ff71d6) ?

Its possible that your install of 'certifi' is fixing this

**Comment by cliffAtOsaic** [comment]
Yes, I confirmed that your changes fix the issue I was experiencing.

I uninstalled 'python-certifi-win32', reproduced the failure, then tested the fix.  Looks good!

**Comment by cliffAtOsaic** [comment]
Looks like all I needed to fix this was to add certifi:

requests>=2.21.0
veracode-api-signing>=19.9.0
certifi==2024.8.30
